// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCH9pN-j5FAd_-BJkU4qpkxZX6sPLxvXqQ',
    appId: '1:134970392054:web:138263b82b59d090bedbd7',
    messagingSenderId: '134970392054',
    projectId: 'uwais-manage',
    authDomain: 'uwais-manage.firebaseapp.com',
    storageBucket: 'uwais-manage.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHSnrVBfhZ-YawCzkQEVBa7EdOZBucJog',
    appId: '1:134970392054:android:61375a474c43957abedbd7',
    messagingSenderId: '134970392054',
    projectId: 'uwais-manage',
    storageBucket: 'uwais-manage.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPqueAYkiwLd3h2Xm9rX-nkAnqsStr-zs',
    appId: '1:134970392054:ios:e0b67b6528170b4cbedbd7',
    messagingSenderId: '134970392054',
    projectId: 'uwais-manage',
    storageBucket: 'uwais-manage.firebasestorage.app',
    iosBundleId: 'com.example.noor',
  );
}
