import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'dart:io';
import '../theme_constants.dart';
import '../models/dua.dart';
import '../models/user_model.dart';
import '../cubit/dua_cubit.dart';
import '../cubit/dua_states.dart';
import '../cubit/user_cubit.dart';
import '../cubit/user_states.dart';
import '../repository/dua_repository.dart';
import 'dua_form_page.dart';

class ManageDuasPage extends StatelessWidget {
  const ManageDuasPage({super.key});

  @override
  Widget build(BuildContext context) {
    // Get the existing UserCubit for admin check
    final existingUserCubit = context.read<UserCubit>();
    
    return BlocProvider(
      create: (_) => DuaCubit(DuaRepository()),
      child: BlocBuilder<UserCubit, UserState>(
        bloc: existingUserCubit,
        builder: (context, userState) {
          // Check if current user is admin using the existing UserCubit
          final currentUser = userState.currentUser;
          final isAdmin = currentUser?.roles.contains(UserType.admin) ?? false;
          
          if (!isAdmin) {
            // Non-admin users should not access this page
            WidgetsBinding.instance.addPostFrameCallback((_) {
              Navigator.of(context).pop();
              ScaffoldMessenger.of(context).showSnackBar(
                SnackBar(
                  content: Text('Akses ditolak: Hanya admin boleh mengakses halaman ini.'),
                  backgroundColor: Theme.of(context).colorScheme.error,
                ),
              );
            });
            return Scaffold(
              appBar: AppBar(
                title: const Text('Urus Doa'),
                backgroundColor: AppColors.appBar,
                foregroundColor: AppColors.onAppBar,
              ),
              body: const Center(
                child: CircularProgressIndicator(),
              ),
            );
          }
          
          // User is admin, fetch duas and show the view
          // Fetch duas only once when admin status is confirmed
          WidgetsBinding.instance.addPostFrameCallback((_) {
            final duaCubit = context.read<DuaCubit>();
            if (duaCubit.state.status == DuaStatus.initial) {
              duaCubit.fetchDuas();
            }
          });
          return const _ManageDuasView();
        },
      ),
    );
  }
}

class _ManageDuasView extends StatelessWidget {
  const _ManageDuasView();

  Future<void> _addDua(BuildContext context) async {
    final newDua = await Navigator.of(context).push<Dua>(
      MaterialPageRoute(builder: (context) => const DuaFormPage()),
    );
    if (newDua != null) {
      context.read<DuaCubit>().addDua(newDua);
    }
  }

  Future<void> _editDua(BuildContext context, Dua dua) async {
    final editedDua = await Navigator.of(context).push<Dua>(
      MaterialPageRoute(builder: (context) => DuaFormPage(initialDua: dua)),
    );
    if (editedDua != null) {
      context.read<DuaCubit>().updateDua(editedDua);
    }
  }

  void _duplicateDua(BuildContext context, Dua dua) async {
    final confirm = await showDialog<bool>(
      context: context,
      builder: (ctx) => AlertDialog(
        title: const Text('Salin Doa'),
        content: Text('Adakah anda pasti mahu menyalin "${dua.title}"?'),
        actions: [
          TextButton(
            onPressed: () => Navigator.of(ctx).pop(false),
            child: const Text('Batal'),
          ),
          ElevatedButton(
            onPressed: () => Navigator.of(ctx).pop(true),
            style: ElevatedButton.styleFrom(
              backgroundColor: Theme.of(context).colorScheme.primary,
            ),
            child: const Text('Salin'),
          ),
        ],
      ),
    );
    
    if (confirm == true) {
      // Create a duplicate dua with empty ID (will be generated by Firestore)
      final duplicatedDua = Dua(
        id: '', // Empty ID - Firestore will generate a new one
        title: '${dua.title} (Copy)',
        content: dua.content,
        image: dua.image,
        link: dua.link,
        notes: dua.notes,
        uploaded: DateTime.now(), // Set to current time for new duplicate
      );
      
      try {
        await context.read<DuaCubit>().addDua(duplicatedDua);
        if (context.mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(
              content: Text('Doa "${dua.title}" telah disalin'),
              backgroundColor: Colors.green, // Success color - keep as is
              behavior: SnackBarBehavior.floating,
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(8),
              ),
            ),
          );
        }
      } catch (e) {
        if (context.mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(
              content: Text('Ralat menyalin doa: $e'),
              backgroundColor: Colors.red,
              behavior: SnackBarBehavior.floating,
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(8),
              ),
            ),
          );
        }
      }
    }
  }

  void _deleteDua(BuildContext context, Dua dua) {
    showDialog(
      context: context,
      builder: (ctx) => AlertDialog(
        title: const Text('Padam Doa'),
        content: const Text('Adakah anda pasti mahu memadam doa ini?'),
        actions: [
          TextButton(
            onPressed: () => Navigator.of(ctx).pop(),
            child: const Text('Batal'),
          ),
          TextButton(
            onPressed: () {
              context.read<DuaCubit>().deleteDua(dua.id);
              Navigator.of(ctx).pop();
            },
            child: Text(
              'Padam',
              style: TextStyle(
                color: Theme.of(context).colorScheme.error,
              ),
            ),
          ),
        ],
      ),
    );
  }

  void _toggleHideDua(BuildContext context, Dua dua) async {
    try {
      await context.read<DuaCubit>().updateDua(
        dua.copyWith(isHidden: !dua.isHidden),
      );
      if (context.mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text(dua.isHidden 
              ? 'Doa telah ditunjukkan kepada pengguna'
              : 'Doa telah disembunyikan daripada pengguna'),
            backgroundColor: Colors.green,
            behavior: SnackBarBehavior.floating,
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(8),
            ),
          ),
        );
      }
    } catch (e) {
      if (context.mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Ralat mengemas kini doa: $e'),
            backgroundColor: Theme.of(context).colorScheme.error,
            behavior: SnackBarBehavior.floating,
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(8),
            ),
          ),
        );
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Urus Doa'),
        backgroundColor: AppColors.appBar,
        foregroundColor: AppColors.onAppBar,
        actions: [
          IconButton(
            icon: const Icon(Icons.add),
            tooltip: 'Tambah Doa',
            onPressed: () => _addDua(context),
          ),
        ],
      ),
      body: BlocBuilder<DuaCubit, DuaState>(
        builder: (context, state) {
          if (state.status == DuaStatus.loading) {
            return const Center(child: CircularProgressIndicator());
          } else if (state.status == DuaStatus.error) {
            // Check if it's a permission error
            final errorMessage = state.error ?? 'An error occurred';
            final isPermissionError = errorMessage.toLowerCase().contains('permission denied') ||
                                     errorMessage.toLowerCase().contains('permission-denied');
            
            return Center(
              child: Padding(
                padding: const EdgeInsets.all(24.0),
                child: Column(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    Icon(
                      isPermissionError ? Icons.lock : Icons.error,
                      color: Theme.of(context).colorScheme.error,
                      size: 48,
                    ),
                    const SizedBox(height: 16),
                    Text(
                      isPermissionError
                          ? 'Akses Ditolak'
                          : 'Ralat Memuatkan Doa',
                      style: TextStyle(
                        fontSize: 20,
                        fontWeight: FontWeight.bold,
                        color: Theme.of(context).colorScheme.error,
                      ),
                    ),
                    const SizedBox(height: 8),
                    Text(
                      isPermissionError
                          ? 'Anda tidak mempunyai kebenaran untuk mengakses halaman ini. Sila pastikan anda log masuk sebagai admin.'
                          : errorMessage,
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        fontSize: 14,
                        color: Theme.of(context).colorScheme.onSurface.withOpacity(0.7),
                      ),
                    ),
                    const SizedBox(height: 24),
                    if (!isPermissionError)
                      ElevatedButton.icon(
                        onPressed: () => context.read<DuaCubit>().fetchDuas(),
                        icon: const Icon(Icons.refresh),
                        label: const Text('Cuba Lagi'),
                        style: ElevatedButton.styleFrom(
                          padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 12),
                        ),
                      ),
                  ],
                ),
              ),
            );
          } else if (state.duas.isEmpty) {
            return Center(
              child: Text(
                'No duas found. Tap + to add.',
                style: TextStyle(color: AppColors.disabled, fontSize: 18),
              ),
            );
          }
          return ListView.builder(
            padding: const EdgeInsets.symmetric(vertical: 16, horizontal: 16),
            itemCount: state.duas.length,
            itemBuilder: (context, i) {
              final dua = state.duas[i];
              return Opacity(
                opacity: dua.isHidden ? 0.6 : 1.0,
                child: Card(
                  elevation: 2,
                  shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
                  color: Theme.of(context).brightness == Brightness.dark ? AppColors.darkCard : AppColors.lightCard,
                  margin: const EdgeInsets.only(bottom: 16),
                  child: Padding(
                    padding: const EdgeInsets.all(16),
                    child: Row(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        if (dua.image != null && dua.image!.isNotEmpty)
                          ClipRRect(
                            borderRadius: BorderRadius.circular(10),
                            child: _buildDuaImage(dua.image!),
                          ),
                        const SizedBox(width: 18),
                        Expanded(
                          child: Column(
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              Row(
                                children: [
                                  Expanded(
                                    child: Text(
                                      dua.title,
                                      style: TextStyle(
                                        color: Theme.of(context).brightness == Brightness.dark ? AppColors.darkText : AppColors.text,
                                        fontWeight: FontWeight.bold,
                                        fontSize: 16,
                                      ),
                                    ),
                                  ),
                                  if (dua.isHidden)
                                    Container(
                                      padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
                                      decoration: BoxDecoration(
                                        color: Colors.grey,
                                        borderRadius: BorderRadius.circular(12),
                                      ),
                                      child: const Text(
                                        'Disembunyikan',
                                        style: TextStyle(
                                          color: Colors.white,
                                          fontSize: 10,
                                          fontWeight: FontWeight.bold,
                                        ),
                                      ),
                                    ),
                                ],
                              ),
                            const SizedBox(height: 8),
                            Text(
                              dua.content,
                              style: TextStyle(
                                color: Theme.of(context).brightness == Brightness.dark ? AppColors.darkText : AppColors.text,
                                fontSize: 14,
                              ),
                            ),
                            if (dua.link != null && dua.link!.isNotEmpty) ...[
                              const SizedBox(height: 8),
                              Text(
                                dua.link!,
                                style: TextStyle(
                                  color: AppColors.primary,
                                  fontSize: 13,
                                  decoration: TextDecoration.underline,
                                ),
                              ),
                            ],
                            if (dua.notes != null && dua.notes!.isNotEmpty) ...[
                              const SizedBox(height: 8),
                              Text(
                                'Notes: ${dua.notes!}',
                                style: TextStyle(
                                  color: AppColors.disabled,
                                  fontSize: 12,
                                  fontStyle: FontStyle.italic,
                                ),
                              ),
                            ],
                          ],
                        ),
                      ),
                      PopupMenuButton<String>(
                        icon: Icon(
                          Icons.more_vert,
                          color: Theme.of(context).colorScheme.primary.withOpacity(0.6),
                        ),
                        onSelected: (value) {
                          switch (value) {
                            case 'edit':
                              _editDua(context, dua);
                              break;
                            case 'duplicate':
                              _duplicateDua(context, dua);
                              break;
                            case 'hide':
                              _toggleHideDua(context, dua);
                              break;
                            case 'delete':
                              _deleteDua(context, dua);
                              break;
                          }
                        },
                        itemBuilder: (context) => [
                          PopupMenuItem(
                            value: 'edit',
                            child: Row(
                              children: [
                                const Icon(Icons.edit, color: Colors.orange, size: 20),
                                const SizedBox(width: 12),
                                const Text('Edit'),
                              ],
                            ),
                          ),
                          PopupMenuItem(
                            value: 'duplicate',
                            child: Row(
                              children: [
                                const Icon(Icons.copy, color: Colors.blue, size: 20),
                                const SizedBox(width: 12),
                                const Text('Duplicate'),
                              ],
                            ),
                          ),
                          PopupMenuItem(
                            value: 'hide',
                            child: Row(
                              children: [
                                Icon(
                                  dua.isHidden ? Icons.visibility : Icons.visibility_off,
                                  color: Colors.grey,
                                  size: 20,
                                ),
                                const SizedBox(width: 12),
                                Text(dua.isHidden ? 'Tunjukkan' : 'Sembunyikan'),
                              ],
                            ),
                          ),
                          PopupMenuItem(
                            value: 'delete',
                            child: Row(
                              children: [
                                Icon(
                                  Icons.delete,
                                  color: Theme.of(context).colorScheme.error,
                                  size: 20,
                                ),
                                const SizedBox(width: 12),
                                const Text('Padam'),
                              ],
                            ),
                          ),
                        ],
                      ),
                    ],
                  ),
                ),
              ),
              );
            },
          );
        },
      ),
    );
  }

  Widget _buildDuaImage(String imagePath) {
    // Check if it's a network URL
    if (imagePath.startsWith('http://') || imagePath.startsWith('https://')) {
      return Image.network(
        imagePath,
        width: 80,
        height: 80,
        fit: BoxFit.cover,
        errorBuilder: (context, error, stackTrace) {
          return Container(
            width: 80,
            height: 80,
            decoration: BoxDecoration(
              color: Theme.of(context).colorScheme.primary.withOpacity(0.1),
              borderRadius: BorderRadius.circular(10),
            ),
            child: Icon(
              Icons.image_not_supported,
              color: Theme.of(context).colorScheme.primary,
              size: 30,
            ),
          );
        },
        loadingBuilder: (context, child, loadingProgress) {
          if (loadingProgress == null) return child;
          return Container(
            width: 80,
            height: 80,
            decoration: BoxDecoration(
              color: Theme.of(context).colorScheme.primary.withOpacity(0.1),
              borderRadius: BorderRadius.circular(10),
            ),
            child: Center(
              child: CircularProgressIndicator(
                value: loadingProgress.expectedTotalBytes != null
                    ? loadingProgress.cumulativeBytesLoaded /
                        loadingProgress.expectedTotalBytes!
                    : null,
              ),
            ),
          );
        },
      );
    }
    // Check if it's a local file path
    else if (imagePath.startsWith('/') || imagePath.contains('\\')) {
      return Image.file(
        File(imagePath),
        width: 80,
        height: 80,
        fit: BoxFit.cover,
        errorBuilder: (context, error, stackTrace) {
          return Container(
            width: 80,
            height: 80,
            decoration: BoxDecoration(
              color: Theme.of(context).colorScheme.primary.withOpacity(0.1),
              borderRadius: BorderRadius.circular(10),
            ),
            child: Icon(
              Icons.image_not_supported,
              color: Theme.of(context).colorScheme.primary,
              size: 30,
            ),
          );
        },
      );
    }
    // Otherwise, treat as asset
    else {
      return Image.asset(
        imagePath,
        width: 80,
        height: 80,
        fit: BoxFit.cover,
        errorBuilder: (context, error, stackTrace) {
          return Container(
            width: 80,
            height: 80,
            decoration: BoxDecoration(
              color: Theme.of(context).colorScheme.primary.withOpacity(0.1),
              borderRadius: BorderRadius.circular(10),
            ),
            child: Icon(
              Icons.image_not_supported,
              color: Theme.of(context).colorScheme.primary,
              size: 30,
            ),
          );
        },
      );
    }
  }
} 