import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import '../theme_constants.dart';
import 'ad_form_page.dart';
import '../models/ad.dart';
import '../cubit/ad_cubit.dart';
import '../cubit/ad_states.dart';
import '../repository/ad_repository.dart';

class ManageAdsPage extends StatelessWidget {
  const ManageAdsPage({super.key});

  @override
  Widget build(BuildContext context) {
    return BlocProvider(
      create: (_) => AdCubit(AdRepository())..fetchAllAds(),
      child: const _ManageAdsView(),
    );
  }
}

class _ManageAdsView extends StatelessWidget {
  const _ManageAdsView();

  Future<void> _addAd(BuildContext context) async {
    final newAd = await Navigator.of(context).push<Ad>(
      MaterialPageRoute(builder: (context) => const AdFormPage()),
    );
    if (newAd != null) {
      context.read<AdCubit>().addAd(newAd);
    }
  }

  Future<void> _editAd(BuildContext context, Ad ad) async {
    final editedAd = await Navigator.of(context).push<Ad>(
      MaterialPageRoute(builder: (context) => AdFormPage(initialAd: ad)),
    );
    if (editedAd != null) {
      context.read<AdCubit>().updateAd(editedAd);
    }
  }

  void _deleteAd(BuildContext context, Ad ad) {
    showDialog(
      context: context,
      builder: (ctx) => AlertDialog(
        title: const Text('Padam Iklan'),
        content: Text('Adakah anda pasti mahu memadam "${ad.title}"?'),
        actions: [
          TextButton(
            onPressed: () => Navigator.of(ctx).pop(),
            child: const Text('Batal'),
          ),
          ElevatedButton(
            onPressed: () {
              if (ad.id != null) {
                context.read<AdCubit>().deleteAd(ad.id!);
              }
              Navigator.of(ctx).pop();
            },
            style: ElevatedButton.styleFrom(
              backgroundColor: Theme.of(context).colorScheme.error,
            ),
            child: const Text('Padam'),
          ),
        ],
      ),
    );
  }

  void _duplicateAd(BuildContext context, Ad ad) async {
    final confirm = await showDialog<bool>(
      context: context,
      builder: (ctx) => AlertDialog(
        title: const Text('Salin Iklan'),
        content: Text('Adakah anda pasti mahu menyalin "${ad.title}"?'),
        actions: [
          TextButton(
            onPressed: () => Navigator.of(ctx).pop(false),
            child: const Text('Batal'),
          ),
          ElevatedButton(
            onPressed: () => Navigator.of(ctx).pop(true),
            style: ElevatedButton.styleFrom(
              backgroundColor: Theme.of(context).colorScheme.primary,
            ),
            child: const Text('Salin'),
          ),
        ],
      ),
    );
    
    if (confirm == true) {
      final duplicatedAd = Ad(
        id: null, // New ID will be generated by Firestore
        title: '${ad.title} (Copy)',
        description: ad.description,
        image: ad.image,
        link: ad.link,
        notes: ad.notes,
        uploaded: DateTime.now(),
        deadline: ad.deadline,
        createdAt: DateTime.now(),
        isActive: ad.isActive,
      );
      
      try {
        context.read<AdCubit>().addAd(duplicatedAd);
        if (context.mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(
              content: Text('Iklan "${ad.title}" telah disalin'),
              backgroundColor: Colors.green,
              behavior: SnackBarBehavior.floating,
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(8),
              ),
            ),
          );
        }
      } catch (e) {
        if (context.mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(
              content: Text('Ralat menyalin iklan: $e'),
              backgroundColor: Theme.of(context).colorScheme.error,
              behavior: SnackBarBehavior.floating,
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(8),
              ),
            ),
          );
        }
      }
    }
  }

  void _toggleHideAd(BuildContext context, Ad ad) async {
    try {
      context.read<AdCubit>().updateAd(
        ad.copyWith(isActive: !ad.isActive),
      );
      if (context.mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text(ad.isActive 
              ? 'Iklan telah disembunyikan daripada pengguna'
              : 'Iklan telah ditunjukkan kepada pengguna'),
            backgroundColor: Colors.green,
            behavior: SnackBarBehavior.floating,
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(8),
            ),
          ),
        );
      }
    } catch (e) {
      if (context.mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Ralat mengemas kini iklan: $e'),
            backgroundColor: Theme.of(context).colorScheme.error,
            behavior: SnackBarBehavior.floating,
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(8),
            ),
          ),
        );
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return BlocConsumer<AdCubit, AdState>(
      listener: (context, state) {
        if (state.error != null) {
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(
              content: Text('Ralat: ${state.error}'),
              backgroundColor: Theme.of(context).colorScheme.error,
              behavior: SnackBarBehavior.floating,
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(8),
              ),
            ),
          );
        }
      },
      builder: (context, state) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Urus Iklan'),
            backgroundColor: Theme.of(context).appBarTheme.backgroundColor,
            foregroundColor: Theme.of(context).appBarTheme.foregroundColor,
        actions: [
              if (state.isLoading)
                Padding(
                  padding: const EdgeInsets.all(16.0),
                  child: SizedBox(
                    width: 20,
                    height: 20,
                    child: CircularProgressIndicator(
                      strokeWidth: 2,
                      valueColor: AlwaysStoppedAnimation<Color>(
                        Theme.of(context).colorScheme.onPrimary,
                      ),
                    ),
                  ),
                ),
          IconButton(
            icon: const Icon(Icons.add),
            tooltip: 'Tambah Iklan',
                onPressed: state.isLoading ? null : () => _addAd(context),
              ),
            ],
          ),
          backgroundColor: Theme.of(context).scaffoldBackgroundColor,
          body: _buildBody(context, state),
        );
      },
    );
  }

  Widget _buildBody(BuildContext context, AdState state) {
    if (state.isLoading && state.ads.isEmpty) {
      return Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            CircularProgressIndicator(
              color: Theme.of(context).colorScheme.primary,
            ),
            const SizedBox(height: 16),
            Text(
              'Memuatkan iklan...',
              style: TextStyle(
                color: Theme.of(context).textTheme.bodyLarge?.color,
              ),
            ),
          ],
        ),
      );
    }

    if (state.ads.isEmpty) {
      return Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Icon(
              Icons.campaign,
              size: 64,
              color: Theme.of(context).colorScheme.primary.withOpacity(0.5),
            ),
            const SizedBox(height: 16),
            Text(
              'Tiada iklan',
              style: TextStyle(
                fontSize: 18,
                color: Theme.of(context).textTheme.titleLarge?.color?.withOpacity(0.7),
              ),
            ),
            const SizedBox(height: 8),
            Text(
              'Tambah iklan pertama menggunakan butang +',
              style: TextStyle(
                color: Theme.of(context).textTheme.bodyMedium?.color?.withOpacity(0.6),
              ),
          ),
        ],
      ),
      );
    }

    return ListView.builder(
        padding: const EdgeInsets.symmetric(vertical: 16, horizontal: 16),
      itemCount: state.ads.length,
        itemBuilder: (context, i) {
        final ad = state.ads[i];
        return Opacity(
          opacity: !ad.isActive ? 0.6 : 1.0,
          child: Card(
            elevation: 2,
            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
            color: Theme.of(context).cardColor,
            margin: const EdgeInsets.only(bottom: 16),
            child: Padding(
              padding: const EdgeInsets.all(16),
              child: Row(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  ClipRRect(
                    borderRadius: BorderRadius.circular(10),
                    child: ad.image != null && ad.image!.isNotEmpty
                        ? (ad.image!.startsWith('http://') || ad.image!.startsWith('https://')
                            ? Image.network(
                                ad.image!,
                                width: 80,
                                height: 80,
                                fit: BoxFit.cover,
                                errorBuilder: (context, error, stackTrace) {
                                  return Container(
                                    width: 80,
                                    height: 80,
                                    decoration: BoxDecoration(
                                      color: Theme.of(context).colorScheme.primary.withOpacity(0.1),
                                      borderRadius: BorderRadius.circular(10),
                                    ),
                                    child: Icon(
                                      Icons.campaign,
                                      color: Theme.of(context).colorScheme.primary,
                                      size: 40,
                                    ),
                                  );
                                },
                                loadingBuilder: (context, child, loadingProgress) {
                                  if (loadingProgress == null) return child;
                                  return Container(
                                    width: 80,
                                    height: 80,
                                    decoration: BoxDecoration(
                                      color: Theme.of(context).colorScheme.primary.withOpacity(0.1),
                                      borderRadius: BorderRadius.circular(10),
                                    ),
                                    child: Center(
                                      child: CircularProgressIndicator(
                                        value: loadingProgress.expectedTotalBytes != null
                                            ? loadingProgress.cumulativeBytesLoaded / loadingProgress.expectedTotalBytes!
                                            : null,
                                      ),
                                    ),
                                  );
                                },
                              )
                            : Image.asset(
                                ad.image!,
                      width: 80,
                      height: 80,
                      fit: BoxFit.cover,
                                errorBuilder: (context, error, stackTrace) {
                                  return Container(
                                    width: 80,
                                    height: 80,
                                    decoration: BoxDecoration(
                                      color: Theme.of(context).colorScheme.primary.withOpacity(0.1),
                                      borderRadius: BorderRadius.circular(10),
                                    ),
                                    child: Icon(
                                      Icons.campaign,
                                      color: Theme.of(context).colorScheme.primary,
                                      size: 40,
                                    ),
                                  );
                                },
                              ))
                        : Container(
                            width: 80,
                            height: 80,
                            decoration: BoxDecoration(
                              color: Theme.of(context).colorScheme.primary.withOpacity(0.1),
                              borderRadius: BorderRadius.circular(10),
                            ),
                            child: Icon(
                              Icons.campaign,
                              color: Theme.of(context).colorScheme.primary,
                              size: 40,
                            ),
                    ),
                  ),
                  const SizedBox(width: 18),
                  Expanded(
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Row(
                          children: [
                            Expanded(
                              child: Text(
                          ad.title,
                          style: TextStyle(
                                  color: Theme.of(context).textTheme.bodyLarge?.color,
                            fontWeight: FontWeight.bold,
                            fontSize: 16,
                          ),
                              ),
                            ),
                            if (!ad.isActive)
                              Container(
                                padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
                                decoration: BoxDecoration(
                                  color: Colors.grey,
                                  borderRadius: BorderRadius.circular(12),
                                ),
                                child: const Text(
                                  'Disembunyikan',
                                  style: TextStyle(
                                    color: Colors.white,
                                    fontSize: 10,
                                    fontWeight: FontWeight.bold,
                                  ),
                                ),
                              ),
                          ],
                        ),
                        if (ad.description != null && ad.description!.isNotEmpty) ...[
                          const SizedBox(height: 8),
                          Text(
                            ad.description!,
                            style: TextStyle(
                              color: Theme.of(context).textTheme.bodyLarge?.color,
                              fontSize: 14,
                            ),
                            maxLines: 2,
                            overflow: TextOverflow.ellipsis,
                          ),
                        ],
                        if (ad.link != null && ad.link!.isNotEmpty) ...[
                        const SizedBox(height: 8),
                        Text(
                            ad.link!,
                          style: TextStyle(
                              color: Theme.of(context).colorScheme.primary,
                            fontSize: 13,
                            decoration: TextDecoration.underline,
                            ),
                            maxLines: 1,
                            overflow: TextOverflow.ellipsis,
                          ),
                        ],
                      ],
                    ),
                  ),
                  PopupMenuButton<String>(
                    icon: Icon(
                      Icons.more_vert,
                      color: Theme.of(context).colorScheme.primary.withOpacity(0.6),
                    ),
                    onSelected: (value) {
                      switch (value) {
                        case 'edit':
                          _editAd(context, ad);
                          break;
                        case 'duplicate':
                          _duplicateAd(context, ad);
                          break;
                        case 'hide':
                          _toggleHideAd(context, ad);
                          break;
                        case 'delete':
                          _deleteAd(context, ad);
                          break;
                      }
                    },
                    itemBuilder: (context) => [
                      PopupMenuItem(
                        value: 'edit',
                        child: Row(
                          children: [
                            const Icon(Icons.edit, color: Colors.orange, size: 20),
                            const SizedBox(width: 12),
                            const Text('Edit'),
                          ],
                        ),
                      ),
                      PopupMenuItem(
                        value: 'duplicate',
                        child: Row(
                          children: [
                            const Icon(Icons.copy, color: Colors.blue, size: 20),
                            const SizedBox(width: 12),
                            const Text('Duplicate'),
                          ],
                        ),
                      ),
                      PopupMenuItem(
                        value: 'hide',
                        child: Row(
                    children: [
                            Icon(
                              ad.isActive ? Icons.visibility_off : Icons.visibility,
                              color: Colors.grey,
                              size: 20,
                            ),
                            const SizedBox(width: 12),
                            Text(ad.isActive ? 'Sembunyikan' : 'Tunjukkan'),
                          ],
                        ),
                      ),
                      PopupMenuItem(
                        value: 'delete',
                        child: Row(
                          children: [
                            Icon(
                              Icons.delete,
                              color: Theme.of(context).colorScheme.error,
                              size: 20,
                            ),
                            const SizedBox(width: 12),
                            const Text('Padam'),
                          ],
                        ),
                      ),
                    ],
                  ),
                ],
              ),
              ),
            ),
          );
        },
    );
  }
} 
